### ISSUE TITLE
Prev/Next gets stuck in a loop

### ISSUE THREAD

**Issue by martinroger** [martinroger/ipodesp32#7]
Alternative Prev/Next/Rewind a few times, it is possible to get them stuck in a loop or completely reversed. Next on the mini becomes Prev and vice versa. 

Affected commit is cb47841

**Comment by APF-MRoger** [comment]
Still some issues after commit 33fed42 . Need to extract serial logs

**Comment by APF-MRoger** [comment]
[Prevnext bug.txt](https://github.com/user-attachments/files/17013873/Prevnext.bug.txt)
Attached some example of weird repetition and change of playStatus when rewinding

**Comment by martinroger** [comment]
Commit 69a8fa6 should be the fix for the issue. Empirical testing shows reasonably robust operation without conflict with other fixes, needs to be confirmed with some Serial Debug logs.

**Comment by martinroger** [comment]
Seems definitively fixed in 719ab09c6c69dd3a6eb89c550ffffab03b6c3533
