### ISSUE TITLE
Track change using SetCurrentTrack need to be inhibited when there is a trackChangeAckPending

### ISSUE THREAD

**Issue by APF-MRoger** [martinroger/ipodesp32#8]
When trackChangeAckPending is live, it is possible to still react to another current track change request. It might be necessary to inhibit those commands if there is a trackChangeAckPending when the command is received.

Also the trackChangeAckPending timeout should be reduced

**Comment by martinroger** [comment]
trackChangeAckPending timeout shows that it should be doable in less than 600ms. However the 1100ms is still comfortable.

**Comment by martinroger** [comment]
Issue seems irrelevant or a rare edge case. Closing for now.
